#DATA TYPES 
#directory
DATATYPES = []
DATATYPE_DATAFRAME = 'df'
DATATYPE_READER = 'reader'
DATATYPE_WRITER = 'writer'
DATATYPE_PREVIEWER = 'previewer'
DATATYPES.extend([
    DATATYPE_DATAFRAME,
    DATATYPE_READER,
    DATATYPE_WRITER,
    DATATYPE_PREVIEWER
])

SETTINGS = []
SETTING_LOG_LEVEL = 'log_level'
SETTINGS.extend([
    SETTING_LOG_LEVEL,
])




    
