#######################################################################################
# Book settings
title                       : Pandas Plotly
author                      : Michael Dawson
copyright                   : "2021"
logo                        : ""  # A path to the book logo
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files        : false

execute:
  execute_notebooks         : "off"
launch_buttons:
  binderhub_url             : ""
repository:
  url                       : https://github.com/mdawso04/pandas-plotly
  path_to_book              : ""
  branch                    : master 
  
#######################################################################################
# HTML-specific settings
html:
  use_issues_button         : true
  use_multitoc_numbering    : false
  
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    